apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vfx-pipeline.fullname" . }}-config
  labels:
    {{- include "vfx-pipeline.labels" . | nindent 4 }}
data:
  config.yaml: |
    mongodb:
      uri: {{ .Values.config.mongodb.uri }}
      database: {{ .Values.config.mongodb.database }}
    
    redis:
      host: {{ .Values.config.redis.host }}
      port: {{ .Values.config.redis.port }}
    
    api:
      host: {{ .Values.config.api.host }}
      port: {{ .Values.config.api.port }}
      workers: {{ .Values.config.api.workers }}
    
    watchdog:
      directory: {{ .Values.config.watchdog.directory }}
    
    multimodal_model:
      model_path: {{ .Values.persistence.models.mountPath }}/best_vfx_model.pt
      features_dir: {{ .Values.persistence.cache.mountPath }}/features
    
    performance:
      max_workers: {{ .Values.config.performance.max_workers }}
      enable_gpu_optimization: {{ .Values.config.performance.enable_gpu_optimization }}
      mixed_precision: {{ .Values.config.performance.mixed_precision }}
      enable_caching: true
      cache_size: 1000
    
    scaling:
      min_workers: 2
      max_workers: {{ .Values.autoscaling.maxReplicas }}
      target_cpu_usage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
      target_memory_usage: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    
    caching:
      enable_memory_cache: true
      enable_disk_cache: true
      enable_redis_cache: true
      max_memory_mb: 1024
      disk_cache_dir: {{ .Values.persistence.cache.mountPath }}/disk
      redis:
        host: {{ .Values.config.redis.host }}
        port: {{ .Values.config.redis.port }}
        db: 1
    
    health_checks:
      interval_seconds: {{ .Values.config.health_checks.interval_seconds }}
      thresholds:
        cpu_percent: {{ .Values.config.health_checks.thresholds.cpu_percent }}
        memory_percent: {{ .Values.config.health_checks.thresholds.memory_percent }}
        disk_percent: 90.0
    
    security:
      enable_rate_limiting: true
      rate_limit_requests: 100
      rate_limit_window: 60
    
    monitoring:
      enable_metrics: true
      metrics_port: 9090
      enable_alerts: true
